### ISSUE TITLE
FR: Way to exclude jar from gazelle resolution

### ISSUE THREAD

**Issue by chrismgrayftsinc** [bazel-contrib/rules_jvm#112]
Our repository has a list of shared maven dependencies that includes a jar (`"org.openapitools:openapi-generator-cli:6.0.0"`) that gazelle thinks would work for a lot of different packages, and this leads to a lot of `gazelle:resolve` lines in our top-level BUILD files.  It would be nice if there was a `gazelle:do-not-resolve` type of annotation that we could use to exclude that one jar.

**Comment by illicitonion** [comment]
Sounds very sensible - can I interest you in putting together a PR?

This is where we parse out the metadata of jar files: https://github.com/bazel-contrib/rules_jvm/blob/087e4034962475da4d84b154734b6bf6164d7932/java/gazelle/private/maven/resolver.go#L24-L51

And this is where we parse out directives: https://github.com/bazel-contrib/rules_jvm/blob/087e4034962475da4d84b154734b6bf6164d7932/java/gazelle/configure.go#L74-L99

Wiring things up between the two should be pretty easy :)

**Comment by chrismgrayftsinc** [comment]
Yeah I can probably do that -- no timeline though.
