### ISSUE TITLE
How to use different maven repository for rule dependencies?

### ISSUE THREAD

**Issue by kriscfoster** [bazel-contrib/rules_jvm#124]
Some companies use an internal mirror for maven dependencies. This means that their CI systems cannot access https://repo1.maven.org. When trying to use `java_junit5_test`, we are seeing the following error:

`java.io.IOException: Error downloading [https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar]`

**Comment by luangong** [comment]
In your `WORKSPACE` file:

```
maven_install(
    artifacts = [...],
    repositories = [...],
    ...
)
```

See https://github.com/bazelbuild/rules_jvm_external#usage for more details.

**Comment by kriscfoster** [comment]
Thank you very much @luangong!
