### ISSUE TITLE
FR: Gazelle flag to pass in maven_install path

### ISSUE THREAD

**Issue by caseyduquettesc** [bazel-contrib/rules_jvm#129]
Was looking at [RegisterFlags](https://github.com/bazel-contrib/rules_jvm/blob/main/java/gazelle/configure.go#L32) and it'd be nice to be able to pass in the path to our maven_install.json file through the command line flags. This would, in theory, allow us to pass in a target label there that bazel could resolve to an actual path for us.

I'm imagining something like this

```bazel
gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
    args = [
        "-java-maven-install-file=$(location @maven_dependencies//:maven_install.json)",
    ],
)
```

My use case is we have a rule that has abstracted away the locking process to avoid potential merge conflicts by managing the file for our devs. However, this means we don't have a stable path to provide the directive in the build file for gazelle.

The workaround I'm exploring now is pointing `//:gazelle` to a genrule instead that copies the maven_install.json to a stable location and then calls gazelle and then removes the file.

**Comment by illicitonion** [comment]
Makes sense - I'd gladly review a PR that added this. Thanks!
