### ISSUE TITLE
Should gazelle be removing runtime_deps?

### ISSUE THREAD

**Issue by caseyduquettesc** [bazel-contrib/rules_jvm#154]
I have noticed that running Gazelle removes any runtime deps that are missing `# keep`. I'm wondering if that's really desired behavior because presumably Gazelle couldn't know what deps a library needs at runtime? Should Gazelle be ignoring that attribute, so we don't need to add `# keeps` everywhere?

For the sake of the discussion, here's an example

```bzl
load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "client",
    visibility = ["//:__subpackages__"],
    runtime_deps = ["@maven//:org_glassfish_jersey_core_jersey_common"],
    deps = ["@maven//:javax_ws_rs_javax_ws_rs_api"],
)
```

Gazelle will always remove `@maven//:org_glassfish_jersey_core_jersey_common` here because it isn't aware that `InternalServerErrorException` tries to dynamically load a class.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/16676170/221700217-e5ecd7d1-4f81-40e6-9757-96253112154f.png">

<img width="873" alt="image" src="https://user-images.githubusercontent.com/16676170/221700743-95222568-57a4-46f9-b53c-a24da54676a7.png">

Was this a deliberate design decision that I'm just not seeing the reason for?

**Comment by stevebarrau** [comment]
Thanks for the ticket @caseyduquettesc. We came to the same conclusion recently. This was not a deliberate design decision, I'll work on a fix for this.
