### ISSUE TITLE
Issues with airgapped usage

### ISSUE THREAD

**Issue by carolosf** [bazel-contrib/rules_jvm#163]
Hi there,

When trying to use the rules in an environment without an internet connection I get this error:
'''
Error in download: java.io.IOException: Error downloading [https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar] 
'''

This happens when running contrib_rules_jvm_setup()

All the other dependencies e.g. apple_rules_lint have been resolved with downloading them with http_archive before loading rules_jvm but not sure how to resolve these maven dependencies. 

Using version 0.11.0.

Ideally there should be a way to use my own maven repo.

**Comment by shs96c** [comment]
Have you tried `bazel fetch //my:target` before closing the Internet connection? That should fix the problem

**Comment by carolosf** [comment]
In an environment with an internet connection a fetch works but I need to copy these dependencies into an environment without an internet connection. Not sure how to find the maven dependencies 'ls $(bazel info output_base)/external ' doesn't show me anything obvious for the contrib_rules_jvm directory that seems to have any jars inside

**Comment by carolosf** [comment]
So up until now with any rules that we have used we have managed to use either the dist dir option in bazel or http_archives in the WORKSPACE file. 

We haven't needed to use bazel fetch/sync for any other rules.

Our maven dependencies generally get downloaded and scanned by an internal maven repository. 

Would it be possible to pass a repositories field to maven_install when setting up the rules?

This would let us keep our current dependency scanning process.

**Comment by carolosf** [comment]
I have found a solution.

https://github.com/bazelbuild/rules_jvm_external/issues/892#issuecomment-1525271966

In my .bazelrc I have added:

```
build --experimental_downloader_config=.bazel_downloader
```
In my .bazel_downloader I have:
```
rewrite repo1.maven.org/maven2/(.*) myrepo.com/subpath/subpath/$1
```
