### ISSUE TITLE
Gazelle with java fails: undefined: btree.NewG

### ISSUE THREAD

**Issue by sfc-gh-kleonhard** [bazel-contrib/rules_jvm#168]
Configuring `"@contrib_rules_jvm//java/gazelle"` and running `bazel run :gazelle`, following the [guide](https://github.com/bazel-contrib/rules_jvm/tree/main/java/gazelle), fails due to a missing btree dependency. This code was added fairly recently: https://github.com/bazel-contrib/rules_jvm/commits/main/java/gazelle/private/sorted_set/btreeset.go

I'm using gazelle v0.29: https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.29.0

Error:

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/contrib_rules_jvm/java/gazelle/private/sorted_set/btreeset.go:9:14: undefined: btree.BTreeG
external/contrib_rules_jvm/java/gazelle/private/sorted_set/btreeset.go:16:27: undefined: btree.Ordered
external/contrib_rules_jvm/java/gazelle/private/sorted_set/btreeset.go:18:15: undefined: btree.NewOrderedG
external/contrib_rules_jvm/java/gazelle/private/sorted_set/btreeset.go:28:47: undefined: btree.LessFunc
external/contrib_rules_jvm/java/gazelle/private/sorted_set/btreeset.go:30:15: undefined: btree.NewG
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/compile: exit status 2
Target //:gazelle failed to build
```

We wire up the workspace as specified in the readme, but the go dependencies appear to be missing?

```
load("@contrib_rules_jvm//:repositories.bzl", "contrib_rules_jvm_deps", "contrib_rules_jvm_gazelle_deps")

contrib_rules_jvm_deps()

contrib_rules_jvm_gazelle_deps()

load("@contrib_rules_jvm//:setup.bzl", "contrib_rules_jvm_setup")

contrib_rules_jvm_setup()

load("@contrib_rules_jvm//:gazelle_setup.bzl", "contrib_rules_jvm_gazelle_setup")

contrib_rules_jvm_gazelle_setup()
```

**Comment by illicitonion** [comment]
I can't reproduce this issue... My guess is that you have some other way of pulling in `com_github_google_btree` as a repository rule in your workspace. Unfortunately, this is sometimes hard to debug where conflicting rules come from.

You could try adding:
```
    go_repository(
        name = "com_github_google_btree",
        importpath = "github.com/google/btree",
        sum = "h1:xf4v41cLI2Z6FxbKm+8Bu+m8ifhj15JuZ9sa0jZCMUU=",
        version = "v1.1.2",
    )
```

to both the very top and bottom of your `WORKSPACE` file, and see if it fixes the issue. If so, the problem is indeed that you need to work out what's pulling in a conflicting version.

**Comment by sfc-gh-kleonhard** [comment]
Thanks! Indeed, by manually fetching and adding the Go dependency via go get + gazelle, the tool was able to run. I have no idea how things are "supposed" to work with dependencies like this and I'm not too invested in finding out!
