### ISSUE TITLE
Need recipe for JUnit @Suite.SuiteClasses with `java_test_suite`

### ISSUE THREAD

**Issue by guw** [bazel-contrib/rules_jvm#193]
Consider the following test suite:
```
@RunWith(Suite.class)				
@Suite.SuiteClasses({				
  SomeTest.class,
  AnotherTest.class,  			
})		

public class MyTestSuite {				
    // how to support this?
}
```

All three types are defined in the same Java package, same directory.

With `test_suffixes = ["Test.java", "TestSuite.java"]` the type `MyTestSuite` cannot be compiled by Bazel because it has neither access to `SomeTest` nor `AnotherTest`.

**Comment by guw** [comment]
Maybe the recommendation should be: **don't use this**.

I think that's ok. Test execution is easier with Bazel and `java_test_suite` because one could run all or select them on the command line.

This might be just a doc issue.

**Comment by tjoneslo** [comment]
If you use the `java_junit5_test` and `java_test_suite` rules from [bazel_config/rules_jvm](https://github.com/bazel-contrib/rules_jvm) this is correctly supported. Please read the documentation about how to configure your repo to use the rules correctly in your repo. Please ping any issues you find in that repo rather than here.

**Comment by guw** [comment]
The documentation for `java_test_suite` is pretty terse. 

Specifically this is a tricky point for users (with the example above):
> With` test_suffixes = ["Test.java", "TestSuite.java"]` the type `MyTestSuite` cannot be compiled 

You cannot support both with a single `java_test_suite` macro call.

**Comment by tjoneslo** [comment]
I never got the Junit5 test suite to compile / run correctly as our use cases never covered it. The closest we got was if you used the Junit `@Tag` on the tests to define which classes / method you wanted to run with which suite. You could then set the `include_tags` and `exclude_tags` on the `java_test_suite` to select the specific tests. 

This would cause a problem if you wanted the same test class in two `java_test_suites` (presumably with different tags). We solved that by writing a wrapper around the `define_test` to de-duplicate the names as needed. 

It shouldn't be hard to make the JUnit 5 runner support that. It just doesn't at this point.
