### ISSUE TITLE
`bazel run //:gazelle` could not find javaparser-wrapper

### ISSUE THREAD

**Issue by chrismgrayftsinc** [bazel-contrib/rules_jvm#29]
When attempting to run `gazelle` I get the following error:

```
12:05PM FTL external/contrib_rules_jvm/java/gazelle/private/javaparser/javaparser.go:29 > could not find javaparser-wrapper
```

rules_jvm version: commit `f1b987eeecaaa457b3d4a4367f7fff734799e95a`
bazel version: both 4.2.1 and 5.1.1

I have confirmed that javaparser-wrapper exists in `bazel-bin`.

**Comment by stevebarrau** [comment]
The java gazelle extension requires a recent version of gazelle. Especially its need https://github.com/bazelbuild/bazel-gazelle/pull/1247 if I recall. Can you share the version of gazelle you are using?

**Comment by chrismgrayftsinc** [comment]
I somehow missed the question attached to this.  Since it's been a long time and I've gotten gazelle running in the meantime, I think it's reasonable to close this issue.
