### ISSUE TITLE
Junit5: XML output does not adhere to JUnit schema

### ISSUE THREAD

**Issue by brian-mcnamara** [bazel-contrib/rules_jvm#293]
Taking a look at TestSuiteXmlRenderer, there are some fields marked required by the JUnit schema that are missing, for example timestamp which by the schema: https://windyroad.com.au/dl/Open%20Source/JUnit.xsd is a required attribute. 

```
<xs:attribute name="timestamp" type="ISO8601_DATETIME_PATTERN" use="required">
<xs:annotation>
<xs:documentation xml:lang="en">when the test was executed. Timezone may not be specified.</xs:documentation>
</xs:annotation>
</xs:attribute>
```

**Comment by shs96c** [comment]
I think this change will be fine to add, and it makes us a little more compatible with the various variants of the JUnit XML format out there.

Sadly, the "JUnit XML" format has multiple different interpretations, all of which differ in subtle ways. Worse, the formats you see in the wild are also different. [We documented how we arrived at the format we use here](https://github.com/bazel-contrib/rules_jvm/blob/main/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5/README.md). The spec we follow [lists the hostname as being optional](https://github.com/junit-team/junit5/blob/main/platform-tests/src/test/resources/jenkins-junit.xsd#L97), but there's no harm in adding this information.

**Comment by brian-mcnamara** [comment]
> I think this change will be fine to add, and it makes us a little more compatible with the various variants of the JUnit XML format out there.
> 
> Sadly, the "JUnit XML" format has multiple different interpretations, all of which differ in subtle ways. Worse, the formats you see in the wild are also different. [We documented how we arrived at the format we use here](https://github.com/bazel-contrib/rules_jvm/blob/main/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5/README.md). The spec we follow [lists the hostname as being optional](https://github.com/junit-team/junit5/blob/main/platform-tests/src/test/resources/jenkins-junit.xsd#L97), but there's no harm in adding this information.

Thanks for taking a look. Agreed that the format is different all around, but always good to try to match the schema that `XML_OUTPUT_FILE` references.
