### ISSUE TITLE
 expects maven_install.json to be in the root folder

### ISSUE THREAD

**Issue by gn-harness** [bazel-contrib/rules_jvm#32]
Tried running this on our open source harness repository: https://github.com/harness/harness-core

and noticed that "blaze run //:gazelle" expects the maven_install.json to be present in the root folder - which is not the case for our repo.

At the same time, @contrib_rules_jvm//java/gazelle/cmd/parsejars has an option to pass in -maven-install flag - probably we can add something similar to the gazelle target too.

**Comment by illicitonion** [comment]
You can add a magic comment to the root BUILD.bazel to configure the plugin:

```starlark
# gazelle:java_maven_install_file project/main_maven_install.json
```

But this is totally undocumented! I'll raise a PR with some documentation for the configuration options :)

**Comment by illicitonion** [comment]
See https://github.com/bazel-contrib/rules_jvm/pull/34 for some docs!
