### ISSUE TITLE
Warning - System::setSecurityManager deprecated in Java 17

### ISSUE THREAD

**Issue by chulkilee** [bazel-contrib/rules_jvm#5]
```
==================== Test output for //crypto/src/test/java/com/hellowd/crypto:Sha256Test:
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.github.bazel_contrib.contrib_rules_jvm.junit5.ActualRunner (file:/private/var/tmp/_bazel_chulki/f3de409d11213140d88cb4bf7c678f64/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/contrib_rules_jvm/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5/junit5-runner.jar)
WARNING: Please consider reporting this to the maintainers of com.github.bazel_contrib.contrib_rules_jvm.junit5.ActualRunner
WARNING: System::setSecurityManager will be removed in a future release
Failures: 0
================================================================================
```

`.bazelrc`

```
build --java_language_version=17
build --java_runtime_version=17
build --tool_java_language_version=17
build --tool_java_runtime_version=17
test --test_output=all
```

`bazel info`

```
java-runtime: OpenJDK Runtime Environment (build 11.0.6+10-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS, mixed mode) by Azul Systems, Inc.
release: release 6.0.0-pre.20211215.3
```

**Comment by shs96c** [comment]
The junit5 runner prevents `System.exit` being called, which means that one test can't prematurely cause an entire test run to finish unexpectedly.

While the `SecurityManager` has been deprecated, there's no replacement yet. [JEP 411](https://openjdk.java.net/jeps/411) has this as one of its goals:

> Evaluate whether new APIs or mechanisms are needed to address specific narrow use cases for which the Security Manager has been employed, such as blocking System::exit.

Since the replacement API has not yet been developed or implemented, I'm not quite sure what to do with this issue. Did you have anything in mind, @chulkilee?

**Comment by chulkilee** [comment]
Thanks @shs96c I found that info later in other projects.

I'm wondering junit5 itself can take options not to exit (upstream change). Otherwise.. probably we can just mention this to the doc. I used `6.0.0-pre.20211215.3`  but apparently it could happen recent Java version with stable Bazel release.
