### ISSUE TITLE
Should lint violations be printed to stderr?

### ISSUE THREAD

**Issue by caseyduquettesc** [bazel-contrib/rules_jvm#65]
We use the bazel event stream in CI to identify why a bazel build failed. It primarily relies on stderr containing the error, but for `spotbugs_test`, the output is printed to stdout.

https://github.com/bazel-contrib/rules_jvm/blob/da93854cba5575e87a3efd76202ce39bf7eb70e9/java/private/spotbugs.bzl#L42

I was wondering if you'd consider using stderr instead?

**Comment by illicitonion** [comment]
Sounds pretty reasonable! I put together https://github.com/bazel-contrib/rules_jvm/pull/66 for this :) Thanks for the report!
