### ISSUE TITLE
Configurable bazel executable path in gazelle extension

### ISSUE THREAD

**Issue by caseyduquettesc** [bazel-contrib/rules_jvm#68]
Like [`bazel-diff`](https://github.com/Tinder/bazel-diff/blob/ed0555b39e6844970c10c79a7d1f7cd3a94b7549/cli/src/main/kotlin/com/bazel_diff/cli/GenerateHashesCommand.kt#L35-L40), it'd be nice to be able to configure the path to bazel.

https://github.com/bazel-contrib/rules_jvm/blob/main/java/gazelle/private/bazel/bazel.go#L28

**Comment by illicitonion** [comment]
The gazelle plugin no longer shells out to `bazel` at all, as of https://github.com/bazel-contrib/rules_jvm/pull/69 :)
